VANTIV_MERCHANT_ID: "merchant_123"
VANTIV_PAYPAGE_ID: ""
VANTIV_USER: 'cyrus'
VANTIV_PASSWORD: 'password'

STRIPE_PUBLISHABLE_KEY: pk_test_UGT6QLveMzeBq3sIRPp5Zann
STRIPE_SECRET_KEY: sk_test_sD4JIzclA81J0FQwGyM6hriO
