VANTIV_MERCHANT_ID: "merchant_123"
VANTIV_PAYPAGE_ID: ""
VANTIV_USER: 'cyrus'
VANTIV_PASSWORD: 'password'

STRIPE_PUBLISHABLE_KEY: pk_test_UGT6QLveMzeBq3sIRPp5Zann
STRIPE_SECRET_KEY: sk_test_sD4JIzclA81J0FQwGyM6hriO

GOOGLE_OAUTH_CLIENT_ID: 259650174710-u8oqb81tb44ng77me313vd6b9u6qsbld.apps.googleusercontent.com
GOOGLE_OAUTH_SECRET: IJKdRK6gFBXSIBVzxo9tlkLe
